# Generated by Django 5.1.4 on 2024-12-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publication_date",
            new_name="publication_year",
        ),
    ]
